service_name: marte-{{ .Values.environment }}
project_name: bazinga-project
product: solar-system
owner: at-ss
environment: dev

replicaCount: 2

image:
  repository: nginx
  tag: latest

containerPort: 80
pathHealthCheck: /healthz
