apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base

patches:
- path: cm.yaml
  target:
    kind: ConfigMap
- path: crb.yaml
  target:
    kind: ClusterRoleBinding
- path: deployment.yaml
  target:
    kind: Deployment
- path: mtwebhookconfig.yaml
  target:
    kind: MutatingWebhookConfiguration
- path: pod.yaml
  target:
    kind: Pod
- path: sa.yaml
  target:
    kind: ServiceAccount
- path: service.yaml
  target:
    kind: Service
- path: sts.yaml
  target:
    kind: StatefulSet