apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: hom

---

apiVersion: v1
kind: ConfigMap
metadata:
  namespace: hom

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
subjects:
- kind: ServiceAccount
  namespace: hom

---

apiVersion: v1
kind: Service
metadata:
  namespace: hom

---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: hom

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  namespace: hom

---

apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
webhooks:
    clientConfig:
      service:
        namespace: hom

---

apiVersion: v1
kind: Pod
metadata:
  namespace: hom