apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../charts

helmCharts:
  - name: mysql
    version: 9.4.0
    repo: https://charts.bitnami.com/bitnami
    releaseName: hello-word
    namespace: default
    valuesFile: values.yaml

