apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../charts

helmCharts:
  - name: cloudecho
    version: 0.1.2
    repo: https://echoyun.xyz/charts/
    releaseName: hello-word
    namespace: default
    valuesFile: values.yaml

