helmGlobals:
  chartHome: charts

helmCharts:
- name: Bazinga
  includeCRDs: false
  valuesInline:
    service_name: teste
    project_name: teste
    product: teste
    owner: teste
    environment: dev

    replicaCount: 2

    image:
      repoitory: busibox
      tag: "1.32.0"
  releaseName: moria
  version: 1.0.0
  repo: https://d90ares.github.io/helm-charts
