helmGlobals:
  chartHome: charts/Bazinga-1.0.0

helmCharts:
- name: Bazinga
  includeCRDs: false
  
  valuesInline:
    service_name: teste
    project_name: teste
    product: teste
    owner: teste
    environment: dev

    replicaCount: 2

    image:
      repository: nginx
      tag: latest

    containerPortName:
      enabled: false

    containerPort: 80
    pathHealthCheck: /healthz
    
  releaseName: moria
  version: 1.0.0
  # repo: https://d90ares.github.io/helm-charts
