apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../charts

helmCharts:
  - name: my-hello
    version: 0.1.2
    repo: https://cloudecho.github.io/charts/
    namespace: default
    valuesFile: values.yaml

