apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../charts

helmCharts:
- name: Bazinga
  namespace: default
  repo: https://d90ares.github.io/helm-charts
