{{ if .Values.env }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s" .Values.service_name .Values.environment | quote }}
  labels:
    app: {{ printf "%s-%s" .Values.service_name .Values.environment | quote }}
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: {{ printf "%s-%s" .Values.service_name .Values.environment | quote }}
    app.kubernetes.io/part-of: {{ .Values.project_name }}
    app.kubernetes.io/version: {{ .Values.image.tag | quote }}
    environment: {{ .Values.environment }}
    version: {{ .Values.image.tag | quote }}
    owner: {{ .Values.owner }}
data:
{{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value  | quote}}
{{- end }}
{{ end }}