{{ if .Values.vault.enabled }}
apiVersion: {{ include "externalsecret.apiVersion" . }}
kind: ExternalSecret
metadata:
  name: {{ printf "%s-%s" .Values.service_name .Values.environment | quote }}
  labels:
    app: {{ printf "%s-%s" .Values.service_name .Values.environment | quote }}
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: {{ printf "%s-%s" .Values.service_name .Values.environment | quote }}
    app.kubernetes.io/part-of: {{ $.Values.project_name }}-{{ .Values.environment }}
    app.kubernetes.io/version: {{ $.Values.image.tag | quote }}
    environment: {{ $.Values.environment }}
    version: {{ $.Values.image.tag | quote }}
    owner: {{ $.Values.owner }}
spec:
  refreshInterval: "5m"
  secretStoreRef:
    kind: ClusterSecretStore
    {{- if .Values.vault.ClusterSecretStore }}
    name: {{ .Values.vault.ClusterSecretStore }}
    {{- else }}
    name: {{ $.Values.environment }}-shared-vault-backend
    {{- end }}
  target:
    name: {{ .Values.service_name }}
  dataFrom:
  {{- if eq (include "externalsecret.apiVersion" $) "external-secrets.io/v1alpha1" }}
  - key: {{ .Values.vault.secretPath }}
  {{- else }}
  - extract:
      key: {{ .Values.vault.secretPath }}
  {{- end }}
{{ end }}