apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ printf "%s-%s" .Values.service_name .Values.environment | quote }}
  labels:
    app: {{ printf "%s-%s" .Values.service_name .Values.environment | quote }}
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: {{ printf "%s-%s" .Values.service_name .Values.environment | quote }}
    app.kubernetes.io/part-of: {{ .Values.project_name | quote }}
    app.kubernetes.io/version: {{ .Values.image.tag | quote }}
    environment: {{ .Values.environment | quote }}
    version: {{ .Values.image.tag | quote }}
    owner: {{ .Values.owner | quote }}